---
title: "Projects in a Shoebox"
---

### [Data Wrangling on OpenStreetMap Data](https://archidemi.github.io/DataWrangling_OpenStreetMap/)

- Wrangled data by Python on an OSM file (~100MB)
- Normalized, extracted informative data about San Diego metro area
- Set up an SQL database and transferred the cleaned dataset
- Presented geographic findings through SQL queries

### [EDA on White Wine Quality](https://archidemi.github.io/EDA_WineQuality/whiteWine.html)

- Explored the wine quality dataset utilizing R (especially ggplot2)
- Delivered insights via descriptive statistics and visualized distributions and relationships
- Discovered what attributes contribute to excellent wine quality

### [Hypothesis Testing on Stroop Effect](https://archidemi.github.io/tTest_StroopEffect/strooptest.html)

- Performed t-Test on the classic cognitive experiment: Stroop Effect
- Interpreted the statistics in step-by-step calculation and "human language"

### [What Makes a Great Baseball Player?](https://public.tableau.com/profile/ssni#!/vizhome/baseball_v2_1/Baseball_Story)

- A Tableau Story narratively shows what attributes contribute to a great baseball player
- Dived into the relationship between batting average and home runs
- Visualized data for reasoning and conclusions on how players' stature and performance on baseball fields correlate

### [Identify Fraud from Enron Email](https://archidemi.github.io/ml_EnronPOIClassifier/)

- A machine learning project to build a classifier that identifies persons of interest based on financial features and email interactions
- Performed feature selection to keep the simplest possible algorithm
- Fine tuned logistic regression to reach an ideal precision score above 0.4